# Generated by Django 3.2.25 on 2024-08-01 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_variant'),
        ('accounts', '0006_alter_wallettransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='order.order'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Online', 'Online'), ('COD', 'Cash on Delivery')], default='Wallet', max_length=20),
            preserve_default=False,
        ),
    ]
