# Generated by Django 3.2.25 on 2024-08-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
